# Generated by Django 4.2.7 on 2023-12-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_account_category_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurring',
        ),
        migrations.CreateModel(
            name='TransactionMetaData',
            fields=[
                ('transaction_meta_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_period', models.DateField()),
                ('first_payment_date', models.DateField()),
                ('final_payment_date', models.DateField()),
                ('previous_payment_date', models.DateField()),
                ('recipient', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.category')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_meta_data_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_meta_data', to='user_api.transactionmetadata'),
        ),
    ]
