# Generated by Django 4.2.7 on 2023-11-30 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_category_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_holder', to='user_api.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
