# Generated by Django 4.2.7 on 2023-12-19 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_recipient_alter_transactionmetadata_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmetadata',
            name='recurring_period',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
