# Generated by Django 4.2.7 on 2023-12-26 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_alter_transactionmetadata_recurring_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmetadata',
            name='final_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmetadata',
            name='previous_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmetadata',
            name='recurring_period',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
