# Generated by Django 4.1.4 on 2024-01-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_remove_transaction_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmetadata',
            name='final_payment_date',
        ),
        migrations.RemoveField(
            model_name='transactionmetadata',
            name='previous_payment_date',
        ),
        migrations.RemoveField(
            model_name='transactionmetadata',
            name='recurring_period',
        ),
    ]
