# Generated by Django 4.2.7 on 2024-01-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_recipient_account_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_meta_data_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.recipient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(choices=[('Utilities', 'Utilities'), ('Food', 'Food'), ('Fast Food', 'Fast Food'), ('Tax', 'Tax'), ('Mortgage', 'Mortgage'), ('Luxury', 'Luxury'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.DeleteModel(
            name='TransactionMetaData',
        ),
    ]
