# Generated by Django 4.2.7 on 2024-01-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0010_remove_transaction_transaction_meta_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
