# Generated by Django 4.2.7 on 2024-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(choices=[('Utilities', 'Utilities'), ('Food', 'Food'), ('Fast Food', 'Fast Food'), ('Tax', 'Tax'), ('Mortgage', 'Mortgage'), ('Luxury', 'Luxury'), ('Other', 'Other'), ('Income', 'Income')], default='Other', max_length=20),
        ),
    ]
